### ISSUE TITLE
Show missing script indicator in Hierarchy 

### ISSUE THREAD

**Issue by pippinmole** [WooshiiDev/HierarchyDecorator#12]

**Comment by WooshiiDev** [comment]
Hey Pippin hope you are well,

Just to clarify, this is to display a warning icon of some form when a script that has no reference or doesn't exist anymore is on an object?

**Comment by pippinmole** [comment]
> 
> 
> Hey Pippin hope you are well,
> 
> Just to clarify, this is to display a warning icon of some form when a script that has no reference or doesn't exist anymore is on an object?

Hi,

The 2nd of the two, when you remove a script from project files, while it is still being used on a gameobject.

Thanks

**Comment by WooshiiDev** [comment]
I've added it to the backlog on the project board [here](https://github.com/WooshiiDev/HierarchyDecorator/projects/1#card-48050856) to work on it
This shouldn't be anything too difficult and I can get this began after the next version push.

Really nice idea, and actually sounds like something Unity could benefit from if they added it by default

**Comment by WooshiiDev** [comment]
Hi Pippin, it's been a while but I've added the warning to indicate if there is a missing script. It can be toggled in the icons section of the settings:

![Unity_15_08_2021_2517](https://user-images.githubusercontent.com/31889435/129470365-d91dcf97-3b2a-47f7-ab9d-bf5fe415a28d.png)

I've went ahead with the standard yellow warning indicator because that's what Unity uses, and the error icon will conflict with some future features coming:

![Unity_15_08_2021_2518](https://user-images.githubusercontent.com/31889435/129470411-51638df9-8b32-4d2a-b2b4-f0fb221e83ed.png)

If there's any issue with this please feel free to reply to this and I'll happily reopen or update the feature.

Cheers, 
Wooshii
