### ISSUE TITLE
Support for Bolt icons

### ISSUE THREAD

**Issue by Thane5** [WooshiiDev/HierarchyDecorator#15]
This is about Bolt, the visual scripting plugin that has recently been aquired by Unity.
I have a a lot og Bolt graphs attached to game objects in my scene, and beeing able to display their icons would make it easier to find them.

**Comment by WooshiiDev** [comment]
Hello Thane, hope you're doing well,

I actually have another issue along the same lines with [this issue here](https://github.com/WooshiiDev/HierarchyDecorator/issues/6).

I'm not particularly sure right now how to integrate this into other packages within unity's systems but I'm 100% willing to add support for any other packages as long as I can find out how to do so.

**Comment by WooshiiDev** [comment]
I'm going ahead and closing this as I've made [an issue specifically for all](https://github.com/WooshiiDev/HierarchyDecorator/issues/23) external package conflicts that are found. If you're able to mention any of them found there so I can take a note of them.

I will link this one on that issue however so it is known and mentioned there.

Cheers,
Wooshii.
