### ISSUE TITLE
Feature Request - allow setting active/inactive for all selected transforms in the hierarchy

### ISSUE THREAD

**Issue by medallyon** [WooshiiDev/HierarchyDecorator#20]
![image](https://user-images.githubusercontent.com/17483199/128161764-1f5f79bc-fa3b-4ffc-88f4-690a2ff49422.png)

In the above image, I selected multiple transforms so that I could bulk-deactivate them, but it only deactivates the one that's clicked.

Although, I did just find out that you can click on the active checkbox in the Inspector, and it'll do what I expected.

**Comment by WooshiiDev** [comment]
I think this is a fantastic quality of life addition.

Even though you've mentioned the inspector, bulk edits would be nice not just for existing functionality, but also for general workflow efficiency. 

I've had ideas for a popup overlay that appears. but have not tested at all due to the restructure going on. If multi-select functionality was added, it would probably be done through something like that.

Cheers for the suggestion, will definitely consider this

**Comment by WooshiiDev** [comment]
Now that active swiping has been added, you can easily toggle instances off by dragging over them, or with a selection. Will be in next release 👏 
![HD_Toggle_Select](https://user-images.githubusercontent.com/31889435/226567553-ec8ba59c-b57f-43a4-b73c-90e2962fa400.gif)
