### ISSUE TITLE
Hierarchy Decorator Bug - Cant unfold at the bottom

### ISSUE THREAD

**Issue by okleeham** [WooshiiDev/HierarchyDecorator#33]
Unity Version

**Describe the bug**
Cant unfold gameobjects which are at the bottom of the hierarchy

**To Reproduce (If applicable)**
Add children to the gameobject at the bottom of the hierarchy
try to unfold gameobject

**Screenshots**

![Imaget](https://i.ibb.co/7yZdBPm/img.png)

**Additional context**

**Comment by WooshiiDev** [comment]
Ah yeah, it's on my todo list, are you on Unity 2020 (or higher)?
Unity has a lack of control over GUI in some cases and even though the foldout you see above is drawn on top of the two-toned background, it isn't actually interactable. It's just visual.

But Unity still detects interaction on it. It's really frustrating. Anyway, I've actually got a fix for it and it should actually be good to go. 

I've noted the issue you're experiencing [here](https://github.com/WooshiiDev/HierarchyDecorator/issues/30#issuecomment-899462586) as this was reported in the last day or so.

I was going to push it with a fix for the flicker that appears but since it's quite serious I'll push it shortly as a quick fix.

Apologies for the issue it is causing!

**Comment by okleeham** [comment]
Hey! I'm using 2020.3 (LTS) .. This is the only issue I've encountered. Look forward to the fix!

**Comment by WooshiiDev** [comment]
Hey there, I've just released a new version [here](https://github.com/WooshiiDev/HierarchyDecorator/releases/tag/v0.8.2)that should fix this for you.

If this persists or comes back in the future I'll reopen the issue. 

Cheers for reporting this, I appreciate it!
~Wooshii
