### ISSUE TITLE
Question: How to mark an item as a header?

### ISSUE THREAD

**Issue by Yecats** [WooshiiDev/HierarchyDecorator#36]
Hello!

I must be missing something here - I have the package installed and I noticed that the styling changed for most items. But I cannot figure out how to mark an item as a header. What am I missing? I'm on 2021.1.12f1.

Thanks!

![image](https://user-images.githubusercontent.com/4108756/130480587-75fb46c0-b5a1-4b8b-b369-dc93d5805c9e.png)

**Comment by Yecats** [comment]
Ah! I Figured it out. The prefix. It might be worth adding a section in your docs about this.

**Comment by WooshiiDev** [comment]
Hey there!

I'm sorry I never replied quickly after you posted this.

In earlier versions of HD, before I updated the Style settings, I had a small prefix beside the style names. I removed this because it looked off, but since I have updated it, it is something I do want to add back - and with what you have said, this ultimately proves it. 

I also had gifs in the readme to sort of explicitly show how the styles/headers work, and that unfortunately is not the case now. When I work on this later today, I'll update the readme to have a gif or two again. This doesn't solve the entire issue but it's at least one step forward.

I've also noticed on the left in the settings, one of the style headers - the subheader - is overlapping the foldout. This might be an issue with Unity v2021.1.X I have missed so I will do a little big of digging and push a hotfix for that 🙂 

I'll add the prefix displayed in the style foldout in the settings, but on top of the gifs in the readme, I'll add a little breakdown for  adding/removing styles.

Even though you sorted it yourself, I appreciate the issue as this has shown some of HD's functionality could clearer.

Thanks again,
~ Wooshii

**Comment by Yecats** [comment]
No worries at all! I knew I had to be missing something since no one else was confused. :) 

I have to say - your plugin is great. The hierarchy looks so much cleaner compared to what I had before. I really love being able to hover over scripts to see what is attached. Wonderful work - thank you!

![image](https://user-images.githubusercontent.com/4108756/130718049-d9bf10c6-d810-4f85-af5d-018a83b92b76.png)

**Comment by WooshiiDev** [comment]
It's amazing to hear that, it's great to know that something I'm able to work on is of use to others🙂 

If you have any future recommendations or feature requests, always feel free to pop an issue on here and I'm always happy to discuss them!
