### ISSUE TITLE
Global options

### ISSUE THREAD

**Issue by CConchelos** [WooshiiDev/HierarchyDecorator#4]
When making changes to any options, the global options all recheck themselves. I only leave "Show Layers" checked, going to another tab and changing something resets all the checkboxes to checked.

**Comment by CConchelos** [comment]
This seemed to be the case on the initial install. I think maybe it needs to build in order for it to take changes? It's not having an issue now, it's retaining the changes, but it was very confusing at first.

**Comment by WooshiiDev** [comment]
Hello there @CConchelos 
Apologies for the delay in response, 

Could you tell me your Unity version as I'm pretty sure this isn't happening in all versions,
thanks
Wooshii ~

**Comment by CConchelos** [comment]
sure, sorry about that. I have been using 2019.4.8f1 and 2019.4.9f1 lately, not sure if I upgraded before I grabbed the decorator. I want to say that also if I change the color of a header, the color does not change until build, which was confusing too. I thought I was doing something wrong.

**Comment by WooshiiDev** [comment]
Hey there CC,
I'm not sure about the issue myself, as I couldn't see this happen in any version I tried it on.

I've taken a note of this on the project board though, so I'll be keeping an eye out in case it keeps occurring 
[Project Board Link](https://github.com/WooshiiDev/HierarchyDecorator/projects/1#card-45670360)

I'm going to close this for now just due to there being no other case of this but will investigate throughout development

Once again, Thanks 
Wooshii~
