### ISSUE TITLE
Bug - Active Swiping maintains click when dragging objects out of hierarchy

### ISSUE THREAD

**Issue by Rekun** [WooshiiDev/HierarchyDecorator#55]
**Current Unity version used**
2020.3.22f1

**Describe the bug**
When dragging something out of the hierarchy, for example, to the Timeline, moving the mouse over the hierarchy again (without any mouse button pressed)  will start to turn off the gameObjects, like if the hierarchy detects that you are still holding the click

**To Reproduce (If applicable)**

Active Swiping must be ON

Drag something from the hierarchy to the timeline, then without clicking again, move the mouse over the boxes to turn off/On the objects 

**Screenshots**

**Additional context**

**Comment by WooshiiDev** [comment]
Hi Rekun,

I've been trying to replicate this in a few different versions (2018.4.x, 2020.3.5f1) and in [0.9.0](https://github.com/WooshiiDev/HierarchyDecorator/tree/v0.9.0) I cleaned up the logic for activation swiping. With that came some logic changes with how active swiping was handled. 

I think this has been fixed, however because I cannot replicate this, would it be possible if you could pull the latest commit from 0.9.0 and see if it still persists. 

Thanks 🙂

**Comment by WooshiiDev** [comment]
Bug has been fixed, pushing to v0.9
